# Generated by Django 5.1.6 on 2025-02-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='Nombres completos')),
                ('fullLastName', models.CharField(max_length=255, verbose_name='Apellidos completos')),
                ('idNumber', models.CharField(max_length=20, verbose_name='Número de Cédula')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo electrónico')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='Número de celular')),
                ('userName', models.CharField(max_length=255, verbose_name='Nombre de usuario')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('userType', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=6, verbose_name='Tipo de Usuario')),
            ],
        ),
    ]
