# Generated by Django 5.1.6 on 2025-02-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMercApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userType',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10, verbose_name='Tipo de Usuario'),
        ),
    ]
