# Generated by Django 5.1.6 on 2025-02-26 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMercApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProduct', models.CharField(choices=[('aguacate', 'Aguacate'), ('banana', 'Banano'), ('brocoli', 'Brócoli'), ('cafe', 'Café'), ('cebolla_cabezona', 'Cebolla Cabezona'), ('cebolla_larga', 'Cebolla Larga'), ('coliflor', 'Coliflor'), ('frijol', 'Frijol'), ('guayaba', 'Guayaba'), ('lechuga', 'Lechuga'), ('limon', 'Limón'), ('lulo', 'Lulo'), ('maiz', 'Maíz'), ('mango', 'Mango'), ('maracuya', 'Maracuyá'), ('naranja', 'Naranja'), ('papa', 'Papa'), ('papaya', 'Papaya'), ('platano', 'Platano'), ('piña', 'Piña'), ('sandia', 'Sandía'), ('tomate', 'Tomate'), ('yuca', 'Yuca'), ('zanahoria', 'Zanahoria')], max_length=30, verbose_name='Nombre del Producto')),
                ('specificName', models.CharField(max_length=100, verbose_name='Nombre Específico')),
                ('maxQuantity', models.IntegerField(verbose_name='Cantidad Máxima')),
                ('minQuantity', models.IntegerField(verbose_name='Cantidad Mínima')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras'), ('unit', 'Unidades')], max_length=10, verbose_name='Unidad de Medida')),
                ('categories', models.CharField(max_length=100)),
                ('sellerId', models.CharField(max_length=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
        ),
    ]
