# Generated by Django 5.1.6 on 2025-02-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMercApp', '0002_productmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='nameProduct',
            new_name='productName',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='categories',
            field=models.CharField(max_length=100, verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sellerId',
            field=models.CharField(max_length=10, verbose_name='Cedula del Vendedor'),
        ),
    ]
