# Generated by Django 5.1.6 on 2025-03-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMercApp', '0002_alter_usermodel_usertype'),
        ('AgroMercApp', '0003_rename_nameproduct_productmodel_productname_and_more'),
    ]

    operations = [
    ]
