# Generated by Django 5.1.6 on 2025-03-19 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMercApp', '0004_merge_20250305_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userType',
            field=models.CharField(choices=[('buyer', 'Comprador'), ('seller', 'Vendedor')], default='buyer', max_length=10, verbose_name='Tipo de Usuario'),
        ),
        migrations.CreateModel(
            name='cartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de adición')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgroMercApp.productmodel', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
