# Generated by Django 5.1.6 on 2025-03-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMercApp', '0005_alter_usermodel_usertype_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='pricePeerUnit',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Precio por Unidad'),
        ),
    ]
