# Generated by Django 5.1.6 on 2025-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMercApp', '0006_productmodel_pricepeerunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=20, verbose_name='Precio por Unidad'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
    ]
