# Generated by Django 5.1.6 on 2025-03-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMercApp', '0007_cartmodel_price_alter_cartmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='price',
        ),
    ]
