# Generated by Django 5.1.6 on 2025-03-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMercApp', '0009_ordelmodel_orderitemmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdelModel',
            new_name='OrderModel',
        ),
    ]
