# Generated by Django 4.2.15 on 2025-05-13 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMercApp', '0011_favoriteproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'verbose_name': 'Producto Favorito', 'verbose_name_plural': 'Productos Favoritos'},
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de adición'),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgroMercApp.productmodel', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
